
version: "3.9"

services:
    postgres:
        image: postgres
        container_name: db-postgres
        environment: 
            POSTGRES_DB: auth-db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - localnet
        restart: unless-stopped
    
    auth-api:
        build: ./auth-api
        container_name: auth-api
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=dev 
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/auth-db
            - SPRING_DATASOURCE_USERNAME=user
            - SPRING_DATASOURCE_PASSWORD=password
            - JWT_SECRET=my-jwt-secret-very-secret-password-12345678910
            - INTERNAL_TOKEN=my-internal-token
        depends_on:
            - postgres
        networks:
            - localnet
        restart: unless-stopped
    
    data-api:
        build: ./data-api
        container_name: data-api
        ports:
            - "8081:8081"
        environment:
            - INTERNAL_TOKEN=my-internal-token
        networks:
            - localnet
        restart: unless-stopped
    
networks:
    localnet:
        name: localnet
        driver: bridge

volumes:
    postgres-data: